version: '3'
services:

  conjur-master:
    image: registry.tld/conjur-appliance:5.0-stable
    container_name: cdemo_conjur-master
    ports:
      - "443:443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - ./seeds:/tmp/seeds

  conjur-standby:
    image: registry.tld/conjur-appliance:5.0-stable
    container_name: cdemo_conjur-standby
    security_opt:
        - "seccomp:unconfined"
    links:
      - conjur-master
    volumes:
      - ./seeds:/tmp/seeds

  conjur-follower:
    image: registry.tld/conjur-appliance:5.0-stable
    container_name: cdemo_conjur-follower
    ports:
      - "8443:443"
    security_opt:
        - "seccomp:unconfined"
    links:
      - conjur-master
    volumes:
      - ./seeds:/tmp/seeds

  conjur-cli:
    image: conjurinc/cli5
    container_name: cdemo_conjur-cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-master
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - ./policies:/src/policies
      - ./certs:/src/certs
    links:
      - conjur-master

  conjur-cli-2:
    image: conjurinc/cli5
    container_name: cdemo_conjur-cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-master
      CONJUR_ACCOUNT: demo
    volumes:
      - ./policies:/src/policies
      - ./certs:/src/certs
    links:
      - conjur-master

  ansible:
    build:
      context: .
      dockerfile: ansible/Dockerfile
    container_name: cdemo_ansible
    volumes:
      - ./playbooks:/src/playbooks
      - ./certs:/src/certs
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - conjur-master
